### ISSUE TITLE
Changing Background of Dashboard

### ISSUE THREAD

**Issue by yagizbarali** [rstudio/flexdashboard#132]
Hi , is there any way to change color of background?

**Comment by stla** [comment]
Hi, you can define some style in a css file. For example
```
.bgred {
  background-color: red;
}
```
in the file `styles.css`. 

Include this file in the metadata:

```
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    css: styles.css
runtime: shiny
```
Then you can use the style for a column like this:

```
Column {.bgred} 
-----------------------------------------------------------------------

This column has a red background.
```
