### ISSUE TITLE
logo not working with `runtime: shiny_prerendered`

### ISSUE THREAD

**Issue by Courvoisier13** [rstudio/flexdashboard#248]
Hi,
The logo option works with `runtime: shiny` but not `runtime: shiny_prerendered`.
Example:

```
---
title: "Logo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: small.png
editor_options: 
  chunk_output_type: console
runtime: shiny
---
```
works and the logo is in the upper left, where I want it.

but it stops working when I do:

```
---
title: "Logo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: small.png
editor_options: 
  chunk_output_type: console
runtime: shiny_prerendered
---
```

in place of the logo image I get a missing file placeholder.
