### ISSUE TITLE
Consider matching heading font and color across elements

### ISSUE THREAD

**Issue by apreshill** [rstudio/flexdashboard#324]
Currently, if you use both `headings-color` and `heading_font`, they don't always match up. I'd expect that all cyan colored headings here would also be in the Fraunces font, for example. (I'd also expect the tabbed panels to be both cyan and Fraunces too, see #323).

```
   theme:
      headings-color: "cyan" 
      heading_font:
        google: Fraunces
```

<img width="1419" alt="Screen Shot 2021-04-09 at 4 52 29 PM" src="https://user-images.githubusercontent.com/12160301/114251145-d41e7300-9954-11eb-9e38-fb98b85f9042.png">
