### ISSUE TITLE
Cannot import custom css when using runtime shiny and a theme is defined in 0.6.0

### ISSUE THREAD

**Issue by koldLight** [rstudio/flexdashboard#402]
Hi,

It looks flexdashboard 0.6.0 is not correctly reading the css external file when using runtime shiny and a bootswatch theme.

Same code works in 0.5.2 but fails in 0.6.0 with the following error:

```
Warning in file(con, "r") :
  cannot open file 'app.css': No such file or directory
Warning: Error in file: cannot open the connection
  143: file
  142: readLines
  141: xfun::read_utf8
  128: base
  127: output_format$pre_knit
  126: render
  125: discover_rmd_resources
  124: find_external_resources
  123: copy_render_intermediates
  122: output_format$intermediates_generator
  121: <Anonymous>
  116: <reactive>
  100: doc
   99: renderUI
   98: func
   85: renderFunc
   84: output$__reactivedoc__
    3: <Anonymous>
    1: rmarkdown::run
```

To reproduce this error, create a project with these two files:

app.Rmd

```
---
title: "Title"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    css: app.css
    theme:
      bootswatch: flatly
---

### Chart 1

```

app.css

```
.chart-wrapper {
  background-color: purple !important;
}
```

And compare 0.5.2 (ok) vs 0.6.0 (error)
