### ISSUE TITLE
bootswatch theme rending secondary color rather than navbar color

### ISSUE THREAD

**Issue by libjohn** [rstudio/flexdashboard#403]
Using either Rmarkdown template "Flex Dahsboard" or "Flex Dahsboard themed with {bslib}" and the bootwatch _sandstone_ theme renders the navbar chartuse (green ; color = #93c54b) rather than a sandstone color.

```
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bootswatch: sandstone
    orientation: columns
    vertical_layout: fill
```

I'm expecting the navbar to be color = #3e3f3a

But instead it's the color of the "success" button  ; color = #93c54b

**Comment by cpsievert** [comment]
As a workaround, you should be able to do:

```yaml
theme:
      bootswatch: sandstone
      navbar-bg: #3e3f3a
```
