### ISSUE TITLE
Bootswatch 5 themes introduce empty space above elements

### ISSUE THREAD

**Issue by jdsher** [rstudio/flexdashboard#440]
Hi,

I'm attempting update an older flexdashboard of mine with a Bootswatch 5 theme, and have noticed a new behavior that seems to only crop up when using 5. An empty space is introduced above rows and columns, no matter the layout style (I've only tried a few, though). Any idea how this can be fixed? Thank you for your work on this package!

As a reprex, you can change the YAML for the "Sales Report with Highcharter" dashboard on the "Examples" page to:

```
---
title: "Sales Report with Highcharter"
author: "Joshua Kunst"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
    theme: 
      version: 5
---
```
