### ISSUE TITLE
css yaml option dont work properly

### ISSUE THREAD

**Issue by jbkunst** [rstudio/flexdashboard#7]
Hi!

I use a custom css style in a flexdashboard document:
```
...

.navbar-brand {
    font-family: 'Pokemon';
    color: "#3662AC";
}

...
```

The font family is applied but no the color.

![screenshot_1](https://cloud.githubusercontent.com/assets/56481/13656654/71dcbdd4-e647-11e5-9db7-5f25756fd3ee.png)

Result: http://jkunst.com/flexdashboard-highcharter-examples/pokemon/
Code: https://github.com/jbkunst/flexdashboard-highcharter-examples/tree/gh-pages/pokemon

**Comment by jjallaire** [comment]
There are a couple of issues here:

1. You can't enclose the color value in quotes; and

2. You need a more specific selector since the navbar is using navbar-inverse. 

This code worked for me:

```css
.navbar-inverse .navbar-brand {
    font-family: 'Pokemon';
    color: #3662AC;
}
```
